In [1]:
import numpy as np

In [113]:
# Bir boyutlu array oluşturma ve inceleme

liste_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(liste_1.dtype)
print(liste_1.shape)
print(liste_1.ndim)
print(liste_1.size)

int32
(10,)
1
10


In [115]:
# 2 ve 3 boyutlu array oluşturma ve inceleme

liste_2 = np.array([[0, 1, 2], [3, 4, 5]]) # 2 boyutlu array incelemesi
print(liste_2.dtype)
print(liste_2.shape)
print(liste_2.ndim)
print(liste_2.size)
print('İlk satırdaki datalar:', liste_2[0, :])
print('Son satır ortadaki data:', liste_2[1,1])
print(liste_2[1:])

liste_3 = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9],[10, 11, 12]],
                  [[13, 14, 15], [16, 17, 18]]]) # 3 boyutlu array incelemesi
print(liste_3.dtype)
print(liste_3.shape)
print(liste_3.ndim)
print(liste_3.size)
print('İlk satırdaki datalar:', liste_3[0,:,:])
print("Veri 10u çağırma:", liste_3[1, 1, 0])
print(liste_3[2::])

int32
(2, 3)
2
6
İlk satırdaki datalar: [0 1 2]
Son satır ortadaki data: 4
[[3 4 5]]
int32
(3, 2, 3)
3
18
İlk satırdaki datalar: [[1 2 3]
 [4 5 6]]
Veri 10u çağırma: 10
[[[13 14 15]
  [16 17 18]]]


In [145]:
# Sıfırlardan ve birlerden oluşan array'ler ve birleştirilmesi

sıfır = np.zeros((2, 3))
print('Sıfır dizesi:\n', sıfır)

bir = np.ones((2, 3))
print('Birler dizesi:\n', bir)

yatay_birlestirme = np.hstack((sıfır, bir))
print('Satır birleştirilmiş yeni dize:\n', yatay_birlestirme)

dikey_birlestirme = np.vstack((sıfır, bir))
print('Sütun birleştirilmiş yeni dize:\n', dikey_birlestirme)

Sıfır dizesi:
 [[0. 0. 0.]
 [0. 0. 0.]]
Birler dizesi:
 [[1. 1. 1.]
 [1. 1. 1.]]
Satır birleştirilmiş yeni dize:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
Sütun birleştirilmiş yeni dize:
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
